title: "Blog Darma Byu"
description: "SEO - Blogger - Gamer"
url: "https://darmabyu.github.io"
baseurl: ""

theme: null
markdown: kramdown

collections:
  posts:
    output: true

permalink: /blog/:title/
